# Generated by Django 4.2 on 2024-09-24 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CipherDataLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("username", models.TextField(help_text="Encrypted username.")),
                ("password", models.TextField(help_text="Encrypted password.")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CipherDataSecureNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("note", models.TextField(help_text="Encrypted secure note.")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cipher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("LOGIN", "Login"), ("SECURE_NOTE", "Secure note")],
                        max_length=25,
                    ),
                ),
                ("name", models.TextField(help_text="Encrypted cipher data name.")),
                ("key", models.CharField(max_length=180)),
                ("data_id", models.PositiveIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="cipher",
            index=models.Index(
                fields=["content_type", "data_id"],
                name="cipher_ciph_content_8bd464_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cipher",
            unique_together={("content_type", "data_id")},
        ),
    ]
