exclude: "/migrations/"
minimum_pre_commit_version: 2.18.0
default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit]

repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: local
    hooks:
    - id: warn-missing-migrations
      name: Check Django missing migration files.
      description: Basically a wrapper for ./scripts/dev/check_missing_migrations
      entry: scripts/pre-commit/warn_missing_migrations
      language: script
      always_run: true
      fail_fast: true
      types: [text]
      verbose: true
      pass_filenames: false
      stages: [pre-push, manual]
