# Generated by Django 4.2 on 2024-12-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authx", "0005_userecc"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
