# Generated by Django 4.2 on 2025-01-01 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authx", "0007_emailverificationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 2, 16, 10, 36, 260578, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
