# Generated by Django 4.2 on 2025-01-02 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authx", "0008_alter_emailverificationtoken_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 3, 11, 27, 39, 943836, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
