# Generated by Django 4.2 on 2025-02-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cipher", "0002_cipher_is_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cipher",
            name="key",
            field=models.TextField(),
        ),
    ]
