# Generated by Django 4.2 on 2025-02-27 08:11

from django.db import migrations
import mp.core.model.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cipher", "0004_cipher_delete_on_cipher_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cipher",
            name="key",
            field=mp.core.model.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name="cipher",
            name="name",
            field=mp.core.model.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name="cipherdatalogin",
            name="password",
            field=mp.core.model.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name="cipherdatalogin",
            name="username",
            field=mp.core.model.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name="cipherdatasecurenote",
            name="note",
            field=mp.core.model.fields.EncryptedField(),
        ),
    ]
