#!/bin/bash

set -o errexit

poetry run python manage.py migrate
poetry run python manage.py createsuperuser --noinput || true
poetry run python manage.py inituser

echo "Running server in local env ..."
exec poetry run python manage.py runserver "0.0.0.0:8000"
