# Generated by Django 4.2 on 2024-09-29 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(default="", max_length=150)),
                (
                    "refresh_token_id",
                    models.CharField(default="", max_length=150, unique=True),
                ),
                ("exp", models.DateTimeField(help_text="Token expiration date.")),
                ("nbf", models.DateTimeField(help_text="Active not before date.")),
                (
                    "replaced_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Another refresh token id.",
                        max_length=150,
                    ),
                ),
                ("revoked", models.BooleanField(default=False)),
                (
                    "datetime_revoked",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
