# Generated by Django 4.2 on 2025-01-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authx", "0010_alter_emailverificationtoken_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
