# Generated by Django 4.2 on 2025-08-10 16:55

from django.db import migrations
import mp.core.model.fields


class Migration(migrations.Migration):

    dependencies = [
        ("authx", "0012_alter_user_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userecc",
            name="key",
            field=mp.core.model.fields.EncryptedTextField(
                help_text="Protected ECC private key."
            ),
        ),
        migrations.AlterField(
            model_name="userecc",
            name="pub",
            field=mp.core.model.fields.EncryptedTextField(help_text="ECC public key."),
        ),
    ]
