# Generated by Django 4.2 on 2025-08-15 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mp.core.model.fields


class Migration(migrations.Migration):

    dependencies = [
        ("authx", "0013_alter_userecc_key_alter_userecc_pub"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSAOAEPKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protected_key",
                    mp.core.model.fields.EncryptedTextField(
                        help_text="Protected private key."
                    ),
                ),
                ("public_key", mp.core.model.fields.EncryptedTextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asymmetric_key",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserECC",
        ),
    ]
