name: Setup python environment.

runs:
  using: "composite"
  steps:

    - name: Install Poetry.
      shell: bash
      run: pipx install poetry==${{ env.CI_POETRY_VERSION }}

    - name: Setup Python.
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.CI_PYTHON_VERSION }}
        cache: 'poetry'
        cache-dependency-path: poetry.lock

    - name: Set Poetry environment.
      shell: bash
      run: poetry env use ${{ env.CI_PYTHON_VERSION }}

    - name: Install dependencies.
      shell: bash
      run: poetry install --no-root
