# Generated by Django 4.2 on 2024-08-25 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authx", "0002_user_hint"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSymmetricKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ("pskey", models.CharField(max_length=128)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usk",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
