# Generated by Django 4.2 on 2024-08-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authx", "0003_user_protected_symmetric_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="protected_symmetric_key",
            field=models.TextField(blank=True, default=""),
        ),
    ]
