# Generated by Django 4.2 on 2024-09-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(default="", max_length=150)),
                ("jti", models.CharField(default="", max_length=150, unique=True)),
                ("exp", models.DateTimeField()),
                ("revoked", models.BooleanField(default=False)),
                (
                    "datetime_revoked",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
