# Generated by Django 4.2 on 2024-09-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refreshtoken",
            name="replaced_by",
            field=models.CharField(
                default="",
                help_text="Another refresh token jti.",
                max_length=150,
                unique=True,
            ),
        ),
    ]
