# Generated by Django 4.2 on 2024-09-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jwt", "0002_refreshtoken_replaced_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="refreshtoken",
            old_name="jti",
            new_name="refresh_token_id",
        ),
    ]
