# Generated by Django 4.2 on 2024-09-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt", "0003_rename_jti_refreshtoken_refresh_token_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="replaced_by",
            field=models.CharField(
                default="", help_text="Another refresh token jti.", max_length=150
            ),
        ),
    ]
