# Generated by Django 4.2.25 on 2025-11-16 16:34

from django.db import migrations
import mp.core.model.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cipher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cipherlogindata",
            name="authenticator_key",
            field=mp.core.model.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
