# Generated by Django 4.2.25 on 2026-04-02 17:34

from django.db import migrations, models
import mp.core.model.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cipher", "0002_cipherlogindata_authenticator_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="CipherDatabaseData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", mp.core.model.fields.EncryptedTextField()),
                (
                    "notes",
                    mp.core.model.fields.EncryptedTextField(blank=True, null=True),
                ),
                ("engine", mp.core.model.fields.EncryptedTextField()),
                ("connection_type", mp.core.model.fields.EncryptedTextField()),
                ("url", mp.core.model.fields.EncryptedTextField(blank=True, null=True)),
                (
                    "host",
                    mp.core.model.fields.EncryptedTextField(blank=True, null=True),
                ),
                (
                    "port",
                    mp.core.model.fields.EncryptedTextField(blank=True, null=True),
                ),
                (
                    "database",
                    mp.core.model.fields.EncryptedTextField(blank=True, null=True),
                ),
                (
                    "username",
                    mp.core.model.fields.EncryptedTextField(blank=True, null=True),
                ),
                (
                    "password",
                    mp.core.model.fields.EncryptedTextField(blank=True, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="cipher",
            name="type",
            field=models.CharField(
                choices=[
                    ("CARD", "Card"),
                    ("LOGIN", "Login"),
                    ("SECURE_NOTE", "Secure note"),
                    ("DATABASE", "Database"),
                ],
                max_length=25,
            ),
        ),
    ]
