# Generated by Django 4.2 on 2025-02-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cipher", "0003_alter_cipher_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="cipher",
            name="delete_on",
            field=models.DateTimeField(
                blank=True,
                help_text="Schedule timestamp to be deleted. If cipher status is DELETED.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cipher",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("ARCHIVED", "Archived"),
                    ("DELETED", "Deleted"),
                ],
                default="ACTIVE",
                max_length=15,
            ),
        ),
    ]
