# Generated by Django 4.2 on 2025-03-06 08:35

from django.db import migrations
import mp.core.model.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cipher", "0005_alter_cipher_key_alter_cipher_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cipher",
            name="is_favorite",
            field=mp.core.model.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="cipher",
            name="status",
            field=mp.core.model.fields.EncryptedTextField(),
        ),
    ]
