# Generated by Django 4.2 on 2025-09-27 12:36

from django.db import migrations, models
import mp.core.model.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cipher", "0006_alter_cipher_is_favorite_alter_cipher_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CipherDataCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", mp.core.model.fields.EncryptedTextField()),
                ("number", mp.core.model.fields.EncryptedTextField()),
                ("brand", mp.core.model.fields.EncryptedTextField()),
                ("exp_month", mp.core.model.fields.EncryptedTextField()),
                ("exp_year", mp.core.model.fields.EncryptedTextField()),
                ("security_code", mp.core.model.fields.EncryptedTextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="cipher",
            name="type",
            field=models.CharField(
                choices=[
                    ("CARD", "Card"),
                    ("LOGIN", "Login"),
                    ("SECURE_NOTE", "Secure note"),
                ],
                max_length=25,
            ),
        ),
    ]
