# Generated by Django 4.2 on 2025-09-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("cipher", "0007_cipherdatacard_alter_cipher_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cipher",
            name="cipher_ciph_content_8bd464_idx",
        ),
        migrations.RenameField(
            model_name="cipher",
            old_name="data_id",
            new_name="object_id",
        ),
        migrations.AlterUniqueTogether(
            name="cipher",
            unique_together={("content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="cipher",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="cipher_ciph_content_751058_idx",
            ),
        ),
    ]
