name: PR test

on:
  pull_request:
    branches: ["main"]

env:
  CI_PYTHON_VERSION: "3.11"
  CI_POETRY_VERSION: "1.8.5"
  APP_ENVIRONMENT: "test"
  DOMAIN: "example.com"
  DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
  DJANGO_SETTINGS_MODULE: "mp.config.test"
  SECRET_KEY: "django-insecure-secret-key"
  DB_SYMMETRIC_KEY: "IFdjlMcWEjpswSDoOhiEhsQXugioBs_Pbg5z1J8G91U="
  ES256_PRIVATE_KEY_PATH: "mp/jwt/tests/resources/keys/private_key.pem"
  ES256_PUBLIC_KEY_PATH: "mp/jwt/tests/resources/keys/public_key.pem"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/envsetup
      - name: Run tests
        run: poetry run pytest .

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/envsetup
      - name: Run staticcheck
        run: scripts/dev/staticcheck
