name: release

on:
  push:
    branches: ["main"]
    tags: ["*"]

jobs:

  build_test:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      image_sha: ${{ steps.build_env.outputs.image_sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Preparing git-hash
        id: build_env
        shell: bash
        run: |
          echo "image_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Preparing metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Logging in to ghrc.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and upload docker image on ghrc.io
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.build_env.outputs.image_sha }}
          labels: ${{ steps.metadata.outputs.labels }}
          target: production
          provenance: false
          build-args: |
            POETRY_INSTALL_OPTS=--no-root
            POETRY_VERSION=1.8.5

  test:
    needs: build_test
    uses: ./.github/workflows/test-template.yml
    with:
      image-sha: ${{ needs.build_test.outputs.image_sha }}
      name: Run unittests
      command: poetry run pytest .

  code-quality:
    needs: build_test
    uses: ./.github/workflows/test-template.yml
    with:
      image-sha: ${{ needs.build_test.outputs.image_sha }}
      name: Run staticcheck
      command: ./scripts/dev/staticcheck

  build:
    needs: ["test", "code-quality"]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Preparing metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Logging in to ghrc.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and upload docker image on ghrc.io
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          labels: ${{ steps.metadata.outputs.labels }}
          target: production
          provenance: false
          build-args: |
            POETRY_INSTALL_OPTS=--no-root --without dev
            POETRY_VERSION=1.8.5
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-cache:${{ github.ref_name }}
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}-cache:${{ github.ref_name }},compression=zstd,mode=max
